# Generated by Django 2.1.4 on 2018-12-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='author',
        ),
    ]
